
import type { Workout, Meal, ScheduleEvent, Product } from '@/lib/types';
import { addDays } from 'date-fns';

export const mockWorkouts: Workout[] = [
  {
    id: '1',
    title: 'Form Shooting',
    category: 'Shooting',
    difficulty: 'Easy',
    duration: 1,
    description: 'Master the fundamentals of your shooting form to build a consistent, reliable jump shot.',
    steps: ['Stand 5 feet from the hoop.', 'Shoot 20 shots with one hand, focusing on follow-through.', 'Take a step back.', 'Shoot 20 more shots with guide hand.', 'Repeat until at the free-throw line.'],
    videoUrl: 'https://www.youtube.com/embed/N4q4bL1I2gY',
    imageId: 'workout-shooting-1',
  },
  {
    id: '2',
    title: 'Stationary Dribbling Series',
    category: 'Ball Handling',
    difficulty: 'Easy',
    duration: 1,
    description: 'Improve your feel for the ball with this series of stationary dribbling drills.',
    steps: ['Pound dribbles, 30 seconds each hand.', 'High-to-low dribbles, 30 seconds each hand.', 'Crossovers, 60 seconds.', 'Between the legs, 60 seconds.'],
    videoUrl: 'https://www.youtube.com/embed/p3w8p-5hODg',
    imageId: 'workout-handling-1',
  },
  {
    id: '3',
    title: 'Defensive Slides',
    category: 'Defense',
    difficulty: 'Medium',
    duration: 1,
    description: 'Enhance your lateral quickness and defensive stamina.',
    steps: ['Start on the baseline.', 'Slide to the elbow, touch the floor.', 'Slide back to the start.', 'Repeat 10 times.'],
    videoUrl: 'https://www.youtube.com/embed/i_y6Tmu1sBg',
    imageId: 'workout-defense-1',
  },
  {
    id: '4',
    title: 'Hill Sprints',
    category: 'Conditioning',
    difficulty: 'Hard',
    duration: 1,
    description: 'Build explosive power and endurance with high-intensity hill sprints.',
    steps: ['Find a steep hill.', 'Sprint up for 15 seconds.', 'Walk down to recover.', 'Repeat 12 times.'],
    videoUrl: 'https://www.youtube.com/embed/3-5_8dYUSaI',
    imageId: 'workout-conditioning-1',
  },
  {
    id: '5',
    title: 'Plyometric Power',
    category: 'Vertical Jump',
    difficulty: 'Hard',
    duration: 1,
    description: 'Increase your vertical leap with explosive plyometric exercises.',
    steps: ['Box jumps, 3 sets of 8.', 'Depth jumps, 3 sets of 5.', 'Tuck jumps, 3 sets of 10.'],
    videoUrl: 'https://www.youtube.com/embed/U2hSH2f22B0',
    imageId: 'workout-jump-1',
  },
];

export const mockMeals: Meal[] = [
    {
        id: '1',
        title: 'Power Oatmeal',
        category: 'Breakfast',
        imageId: 'meal-breakfast-1',
        ingredients: ['1/2 cup Rolled Oats', '1 cup Water or Milk', '1 scoop Protein Powder', '1 tbsp Chia Seeds', 'Handful of Berries'],
        steps: ['Bring water/milk to a boil.', 'Add oats and reduce heat.', 'Cook for 5-7 minutes, stirring occasionally.', 'Mix in protein powder and chia seeds.', 'Top with berries.'],
        calories: 450,
        protein: 35,
        carbs: 55,
        fat: 10,
    },
    {
        id: '2',
        title: 'Grilled Chicken Salad',
        category: 'Lunch',
        imageId: 'meal-lunch-1',
        ingredients: ['150g Grilled Chicken Breast', '100g Mixed Greens', '50g Cherry Tomatoes', '1/4 Cucumber', '2 tbsp Vinaigrette'],
        steps: ['Chop cooked chicken breast.', 'Combine all vegetables in a bowl.', 'Add chicken and drizzle with vinaigrette.'],
        calories: 400,
        protein: 40,
        carbs: 10,
        fat: 22,
    },
    {
        id: '3',
        title: 'Recovery Salmon',
        category: 'Dinner',
        imageId: 'meal-dinner-1',
        ingredients: ['180g Salmon Fillet', '150g Quinoa (cooked)', '100g Asparagus', '1 tbsp Olive Oil', 'Lemon & Herbs'],
        steps: ['Season salmon and bake at 200°C for 12-15 mins.', 'Toss asparagus with olive oil and roast with salmon.', 'Serve salmon and asparagus over a bed of quinoa.'],
        calories: 600,
        protein: 45,
        carbs: 40,
        fat: 30,
    },
    {
        id: '4',
        title: 'Greek Yogurt Bowl',
        category: 'Snacks',
        imageId: 'meal-snack-1',
        ingredients: ['200g Greek Yogurt', '1 tbsp Honey', '20g Almonds', 'Handful of Blueberries'],
        steps: ['Add yogurt to a bowl.', 'Drizzle with honey.', 'Top with almonds and blueberries.'],
        calories: 350,
        protein: 25,
        carbs: 30,
        fat: 15,
    },
    {
        id: '5',
        title: 'Post-Game Protein Shake',
        category: 'Post-game',
        imageId: 'meal-snack-1',
        ingredients: ['1 scoop Whey Protein', '1 Banana', '250ml Almond Milk', '1 tbsp Peanut Butter'],
        steps: ['Combine all ingredients in a blender.', 'Blend until smooth.', 'Serve immediately for best results.'],
        calories: 420,
        protein: 30,
        carbs: 45,
        fat: 15,
    }
];

export const mockSchedule: ScheduleEvent[] = [
    { id: 'event-1', userId: 'user-1', date: new Date(), type: 'workout', title: 'Plyometric Power', workoutId: '5' },
    { id: 'event-2', userId: 'user-1', date: addDays(new Date(), 2), type: 'workout', title: 'Form Shooting', workoutId: '1' },
    { id: 'event-3', userId: 'user-1', date: addDays(new Date(), 4), type: 'rest', title: 'Rest Day' },
    { id: 'event-4', userId: 'user-2', date: new Date(), type: 'workout', title: 'Stationary Dribbling Series', workoutId: '2' },
    { id: 'event-5', userId: 'user-2', date: addDays(new Date(), 1), type: 'workout', title: 'Defensive Slides', workoutId: '3' },
    { id: 'event-6', userId: 'user-2', date: addDays(new Date(), 3), type: 'game', title: 'Game Day' },
    { id: 'event-10', userId: 'user-2', date: new Date(), type: 'meal', title: 'Power Oatmeal', mealId: '1'},
    { id: 'event-11', userId: 'user-2', date: new Date(), type: 'meal', title: 'Grilled Chicken Salad', mealId: '2'},
    { id: 'event-12', userId: 'user-2', date: addDays(new Date(),1), type: 'meal', title: 'Recovery Salmon', mealId: '3'},
    { id: 'event-7', userId: 'user-3', date: new Date(), type: 'workout', title: 'Hill Sprints', workoutId: '4' },
    { id: 'event-8', userId: 'user-3', date: addDays(new Date(), 1), type: 'rest', title: 'Rest Day' },
    { id: 'event-9', userId: 'user-3', date: addDays(new Date(), 2), type: 'workout', title: 'Form Shooting', workoutId: '1' },
    { id: 'event-13', userId: 'user-5', date: new Date(), type: 'meal', title: 'Post-Game Protein Shake', mealId: '5' },
];

export const mockProducts: Product[] = [
  {
    id: 'prod-hat',
    name: 'Baseline Pro Hat',
    description: 'A classic snapback hat with the official Baseline logo embroidered on the front. Perfect for on and off the court.',
    imageId: 'merch-hat',
    priceXp: 30,
    priceCash: 20,
  },
  {
    id: 'prod-shirt',
    name: 'Baseline Performance Tee',
    description: 'Lightweight, breathable fabric to keep you cool and dry during intense training sessions. Features the official Baseline logo.',
    imageId: 'merch-tee',
    priceXp: 50,
    priceCash: 25,
  },
  {
    id: 'prod-bottle',
    name: 'Baseline Water Bottle',
    description: 'Stay hydrated with this 32oz insulated water bottle. Keeps your drinks cold for hours. BPA-free with a non-slip grip.',
    imageId: 'merch-bottle',
    priceXp: 100,
    priceCash: 30,
  },
  {
    id: 'prod-2',
    name: 'Baseline Elite Hoodie',
    description: 'A comfortable and stylish hoodie perfect for pre-game warmups or post-game relaxation. Premium soft-fleece interior.',
    imageId: 'merch-hoodie',
    priceXp: 3000,
    priceCash: 50,
  },
  {
    id: 'prod-3',
    name: 'Baseline Pro Reversible Jersey',
    description: 'Game-ready reversible jersey. One side features the classic Baseline blue, the other a crisp white. Made with moisture-wicking material.',
    imageId: 'merch-jersey',
    priceXp: 2500,
    priceCash: 40,
  },
];

    
