
import type { Workout, Meal } from '@/lib/types';

export const mockWorkouts: Workout[] = [
  {
    id: '1',
    title: 'Form Shooting',
    category: 'Shooting',
    difficulty: 'Easy',
    duration: 5,
    description: 'Master the fundamentals of your shooting form to build a consistent, reliable jump shot.',
    steps: ['Stand 5 feet from the hoop.', 'Shoot 20 shots with one hand, focusing on follow-through.', 'Take a step back.', 'Shoot 20 more shots with guide hand.', 'Repeat until at the free-throw line.'],
    videoUrl: 'https://www.youtube.com/embed/07qj8v3ZfS8',
    imageId: 'workout-shooting-1',
  },
  {
    id: '2',
    title: 'Stationary Dribbling Series',
    category: 'Ball Handling',
    difficulty: 'Easy',
    duration: 5,
    description: 'Improve your feel for the ball with this series of stationary dribbling drills.',
    steps: ['Pound dribbles, 30 seconds each hand.', 'High-to-low dribbles, 30 seconds each hand.', 'Crossovers, 60 seconds.', 'Between the legs, 60 seconds.'],
    videoUrl: 'https://www.youtube.com/embed/y2s-3p6yI-4',
    imageId: 'workout-handling-1',
  },
  {
    id: '3',
    title: 'Defensive Slides',
    category: 'Defense',
    difficulty: 'Medium',
    duration: 5,
    description: 'Enhance your lateral quickness and defensive stamina.',
    steps: ['Start on the baseline.', 'Slide to the elbow, touch the floor.', 'Slide back to the start.', 'Repeat 10 times.'],
    videoUrl: 'https://www.youtube.com/embed/Jv1J0C4G0-A',
    imageId: 'workout-defense-1',
  },
  {
    id: '4',
    title: 'Hill Sprints',
    category: 'Conditioning',
    difficulty: 'Hard',
    duration: 5,
    description: 'Build explosive power and endurance with high-intensity hill sprints.',
    steps: ['Find a steep hill.', 'Sprint up for 15 seconds.', 'Walk down to recover.', 'Repeat 12 times.'],
    videoUrl: 'https://www.youtube.com/embed/5-3p9YnS_xA',
    imageId: 'workout-conditioning-1',
  },
  {
    id: '5',
    title: 'Plyometric Power',
    category: 'Vertical Jump',
    difficulty: 'Hard',
    duration: 5,
    description: 'Increase your vertical leap with explosive plyometric exercises.',
    steps: ['Box jumps, 3 sets of 8.', 'Depth jumps, 3 sets of 5.', 'Tuck jumps, 3 sets of 10.'],
    videoUrl: 'https://www.youtube.com/embed/h2S_n0iS4oY',
    imageId: 'workout-jump-1',
  },
];

export const mockMeals: Meal[] = [
    {
        id: '1',
        title: 'Power Oatmeal',
        category: 'Breakfast',
        imageId: 'meal-breakfast-1',
        ingredients: ['1/2 cup Rolled Oats', '1 cup Water or Milk', '1 scoop Protein Powder', '1 tbsp Chia Seeds', 'Handful of Berries'],
        steps: ['Bring water/milk to a boil.', 'Add oats and reduce heat.', 'Cook for 5-7 minutes, stirring occasionally.', 'Mix in protein powder and chia seeds.', 'Top with berries.'],
        calories: 450,
        protein: 35,
        carbs: 55,
        fat: 10,
    },
    {
        id: '2',
        title: 'Grilled Chicken Salad',
        category: 'Lunch',
        imageId: 'meal-lunch-1',
        ingredients: ['150g Grilled Chicken Breast', '100g Mixed Greens', '50g Cherry Tomatoes', '1/4 Cucumber', '2 tbsp Vinaigrette'],
        steps: ['Chop cooked chicken breast.', 'Combine all vegetables in a bowl.', 'Add chicken and drizzle with vinaigrette.'],
        calories: 400,
        protein: 40,
        carbs: 10,
        fat: 22,
    },
    {
        id: '3',
        title: 'Recovery Salmon',
        category: 'Dinner',
        imageId: 'meal-dinner-1',
        ingredients: ['180g Salmon Fillet', '150g Quinoa (cooked)', '100g Asparagus', '1 tbsp Olive Oil', 'Lemon & Herbs'],
        steps: ['Season salmon and bake at 200°C for 12-15 mins.', 'Toss asparagus with olive oil and roast with salmon.', 'Serve salmon and asparagus over a bed of quinoa.'],
        calories: 600,
        protein: 45,
        carbs: 40,
        fat: 30,
    },
    {
        id: '4',
        title: 'Greek Yogurt Bowl',
        category: 'Snacks',
        imageId: 'meal-snack-1',
        ingredients: ['200g Greek Yogurt', '1 tbsp Honey', '20g Almonds', 'Handful of Blueberries'],
        steps: ['Add yogurt to a bowl.', 'Drizzle with honey.', 'Top with almonds and blueberries.'],
        calories: 350,
        protein: 25,
        carbs: 30,
        fat: 15,
    },
    {
        id: '5',
        title: 'Post-Game Protein Shake',
        category: 'Post-game',
        imageId: 'meal-snack-1',
        ingredients: ['1 scoop Whey Protein', '1 Banana', '250ml Almond Milk', '1 tbsp Peanut Butter'],
        steps: ['Combine all ingredients in a blender.', 'Blend until smooth.', 'Serve immediately for best results.'],
        calories: 420,
        protein: 30,
        carbs: 45,
        fat: 15,
    }
];
